sudo: required

services:
  - docker

before_install:
  - docker-compose -f dev.yml up -d --build datosgobar
  - docker exec andino bash /etc/ckan_init.d/tests/install_solr4.sh

script:
  - docker exec datosgobar bash -c 'su -c "bash /etc/ckan_init.d/tests/init_tests.sh; bash /etc/ckan_init.d/tests/run_tests.sh" -l $USER'
