sudo: required

services:
  - docker

before_install:
  - docker-compose -f dev.yml up -d --build datosgobat
  - docker exec datosgobar bash /etc/ckan_init.d/make_test_conf.sh

script:
  - docker exec datosgobar bash -c 'su -c "/etc/ckan_init.d/run_tests.sh" -l $USER'
