site_name: Portal Datos.gob.ar
pages:
  - Home: 'index.md'
  - Instalacion: 'setup/install.md'
  - Uso: 'setup/usage.md'
  - Desarrollo:
    - Docker: 'development/docker.md'
    - Tests: 'development/tests.md'
